IF EXISTS
(
    SELECT TOP 1
           s.SPECIFIC_NAME
    FROM INFORMATION_SCHEMA.ROUTINES s
    WHERE s.ROUTINE_TYPE = 'PROCEDURE'
          AND s.ROUTINE_NAME = 'USP_COMANDA_VALIDA_CARACTERISTICA'
)
BEGIN
    DROP PROC [dbo].[USP_COMANDA_VALIDA_CARACTERISTICA];
END;
GO
/*
DECLARE @DATO CHAR(2)
EXEC USP_COMANDA_VALIDA_CARACTERISTICA '01','20250401','100',11, @DATO OUTPUT
SELECT @DATO

DECLARE @DATO BIT
EXEC USP_COMANDA_VALIDA_CARACTERISTICA '01','20250401','100',12, @DATO OUTPUT
SELECT @DATO
*/
CREATE PROCEDURE [dbo].[USP_COMANDA_VALIDA_CARACTERISTICA]
    @CODCIA CHAR(2),
    @FECHA DATE,
    @NUMSER VARCHAR(3),
    @NUMFAC BIGINT,
    @PROCEDE BIT OUT
WITH ENCRYPTION
AS
SET NOCOUNT ON;

DECLARE @cantItemsCaracteristica TINYINT;
DECLARE @cantItemsConCaracteristica TINYINT;

SET @PROCEDE = 0;

SELECT @cantItemsCaracteristica = COUNT(*)
FROM
(
    SELECT DISTINCT
           a.ART_KEY,
           p.PED_NUMSEC
    FROM dbo.PEDIDOS p WITH (NOLOCK)
        INNER JOIN dbo.ARTI a WITH (NOLOCK)
            ON p.PED_CODCIA = a.ART_CODCIA
               AND p.PED_CODART = a.ART_KEY
        INNER JOIN dbo.SUBFAMILIA_CARACTERISTICA sc WITH (NOLOCK)
            ON p.PED_CODCIA = sc.CODCIA
               AND a.ART_SUBFAM = sc.IDSUBFAMILIA
    WHERE p.PED_ESTADO = 'N'
          AND p.PED_CODCIA = @CODCIA
          AND p.PED_NUMSER = @NUMSER
          AND p.PED_NUMFAC = @NUMFAC
          AND CONVERT(CHAR(8), p.PED_FECHA, 112) = @FECHA
) AS Subconsulta;


SELECT @cantItemsConCaracteristica = COUNT(pc.FECHA)
FROM dbo.PEDIDOS_CARACTERISTICAS pc WITH (NOLOCK)
WHERE pc.CODCIA = @CODCIA
      AND pc.NUMSER = @NUMSER
      AND pc.NUMFAC = @NUMFAC
      AND CONVERT(CHAR(8), pc.FECHA, 112) = @FECHA;



IF @cantItemsCaracteristica = @cantItemsConCaracteristica
BEGIN
    SET @PROCEDE = 1;
END;
GO