IF EXISTS
(
    SELECT TOP 1
           s.SPECIFIC_NAME
    FROM INFORMATION_SCHEMA.ROUTINES s
    WHERE s.ROUTINE_TYPE = 'PROCEDURE'
          AND s.ROUTINE_NAME = 'USP_COMANDA_ITEMS_COMBO'
)
BEGIN
    DROP PROC [dbo].[USP_COMANDA_ITEMS_COMBO];
END;
GO
/*
USP_COMANDA_ITEMS_COMBO '01',157
*/
CREATE PROCEDURE [dbo].[USP_COMANDA_ITEMS_COMBO]
    @CODCIA CHAR(2),
    @CODART BIGINT
WITH ENCRYPTION
AS
SET NOCOUNT ON;


SELECT p.PA_CODART AS 'Codigo',
       '==> ' + CAST(CAST(p.PA_PROM AS NUMERIC(6, 2)) AS VARCHAR(10)) + ' -  ' + RTRIM(LTRIM(a.ART_NOMBRE)) AS 'Descripcion'
--  pr.pre_unidad AS 'Unidad' ,
-- ar.ARM_COSPRO as 'CostoUnit',
--  ar.ARM_COSPRO*p.pa_prom as 'Costo'
FROM PAQUETES p
    INNER JOIN ARTI a
        ON p.PA_CODCIA = a.ART_CODCIA
           AND p.PA_CODART = a.ART_KEY
    INNER JOIN PRECIOS pr
        ON p.PA_CODCIA = pr.PRE_CODCIA
           AND p.PA_CODART = pr.PRE_CODART
    INNER JOIN ARTICULO ar
        ON p.PA_CODCIA = ar.ARM_CODCIA
           AND p.PA_CODART = ar.ARM_CODART
WHERE PA_CODPA = @CODART
      AND PA_CODCIA = @CODCIA;


GO
