ALTER TABLE dbo.PARGEN ADD PAR_SERVICIO INT DEFAULT 0;
ALTER TABLE dbo.PARGEN ADD PAR_ICBPER DECIMAL(6,2) DEFAULT 0;
ALTER TABLE dbo.ALLOG ADD ALL_SERVICIO MONEY DEFAULT 0;
ALTER TABLE dbo.ARTI ADD ART_BOLSAS INT DEFAULT 0;
ALTER TABLE dbo.ARTI ADD ART_CODBOLSA BIGINT DEFAULT NULL;
GO
UPDATE dbo.PARGEN SET PAR_SERVICIO=10
UPDATE dbo.PARGEN SET PAR_ICBPER = 10


select * from PARGEN