--SELECT * FROM COMPROBANTE_FORMAPAGO
--ORDER BY CODCIA,TIPODOCTO, SERIE,NUMERO

alter table COMPROBANTE_FORMAPAGO ADD CORRELATIVO INT;
GO
DECLARE @TBLDATOS TABLE(CODCIA CHAR(2),TIPODOCTO CHAR(1), SERIE VARCHAR(3),NUMERO BIGINT, IDFORMAPAGO INT, CORRELATIVO INT)


INSERT INTO @TBLDATOS
SELECT CODCIA,TIPODOCTO,SERIE,NUMERO,IDFORMAPAGO,
ROW_NUMBER() OVER (PARTITION BY CODCIA,TIPODOCTO, SERIE,NUMERO ORDER BY CODCIA,TIPODOCTO, SERIE,NUMERO) 
FROM COMPROBANTE_FORMAPAGO;



MERGE into COMPROBANTE_FORMAPAGO AS tg
using @TBLDATOS as sc
on tg.codcia = sc.codcia and tg.tipodocto = sc.tipodocto and tg.serie = sc.serie and tg.numero = sc.numero and tg.idformapago = sc.idformapago
WHEN MATCHED THEN
update set
tg.correlativo = sc.correlativo
;