USE [BDATOS]
GO
/****** Object:  Table [dbo].[COMPROBANTE_FORMAPAGO]    Script Date: 6/07/2024 11:03:04 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO



CREATE TABLE [dbo].[COMPROBANTE_FORMAPAGO](
	[CODCIA] [char](2) NOT NULL,
	[TIPODOCTO] [char](1) NOT NULL,
	[SERIE] [varchar](3) NOT NULL,
	[NUMERO] [bigint] NOT NULL,
	[IDFORMAPAGO] [int] NOT NULL,
	[MONTO] [money] NOT NULL,
	[REFERENCIA] [varchar](40) NULL,
	[DIASCREDITO] [int] NULL,
	[ACTIVO] [bit] NOT NULL,
	[CU_REGISTER] [varchar](20) NOT NULL,
	[FE_REGISTER] [datetime] NOT NULL,
	[CU_DELETE] [varchar](20) NULL,
	[FE_DELETE] [datetime] NULL,
 CONSTRAINT [PK_COMPROBANTE_FORMAPAGO] PRIMARY KEY CLUSTERED 
(
	[CODCIA] ASC,
	[TIPODOCTO] ASC,
	[SERIE] ASC,
	[NUMERO] ASC,
	[IDFORMAPAGO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[COMPROBANTE_FORMAPAGO] ADD  CONSTRAINT [DF__COMPROBAN__REFER__216CB7F1]  DEFAULT (NULL) FOR [REFERENCIA]
GO
ALTER TABLE [dbo].[COMPROBANTE_FORMAPAGO] ADD  CONSTRAINT [DF_COMPROBANTE_FORMAPAGO_DIASCREDITO]  DEFAULT ((0)) FOR [DIASCREDITO]
GO
ALTER TABLE [dbo].[COMPROBANTE_FORMAPAGO] ADD  CONSTRAINT [DF_COMPROBANTE_FORMAPAGO_ACTIVO]  DEFAULT ((1)) FOR [ACTIVO]
GO
ALTER TABLE [dbo].[COMPROBANTE_FORMAPAGO] ADD  CONSTRAINT [DF_COMPROBANTE_FORMAPAGO_FE_REGISTER]  DEFAULT (getdate()) FOR [FE_REGISTER]
GO


