/*
SP_FAMILIA_MODIFICAR '01'
*/
ALTER PROC SP_FAMILIA_MODIFICAR
    (
      @CODCIA CHAR(2) ,
      @DENOMINACION VARCHAR(50) ,
      @IMPRESORA VARCHAR(50) ,
      @IMPRESORA2 VARCHAR(50) ,
      @GRUPO CHAR(1),
      @DSCTO MONEY,
       @VISIBLE BIT,
      @CODIGO INT 
    )
AS
    SET NOCOUNT ON 

    UPDATE  dbo.TABLAS
    SET     TAB_NOMLARGO = @DENOMINACION,IMPRESORA = @IMPRESORA, GRUPO = @GRUPO,tab_descuento = @DSCTO,TAB_VISIBLE = @VISIBLE,IMPRESORA2 = @IMPRESORA2
    WHERE   TAB_TIPREG = 122
            AND TAB_CODCIA = @CODCIA
            AND TAB_NUMTAB = @CODIGO
GO