IF EXISTS ( SELECT  *
            FROM    INFORMATION_SCHEMA.routines
            WHERE   routine_type = 'PROCEDURE'
                    AND ROUTINE_NAME = 'SP_FAMILIA_ELIMINAR' )
    DROP PROCEDURE SP_FAMILIA_ELIMINAR
GO
/*
SP_FAMILIA_ELIMINAR '01'
*/
CREATE PROC SP_FAMILIA_ELIMINAR
    (
      @CODCIA CHAR(2) ,
      @CODIGO INT 
    )
AS
    SET NOCOUNT ON 

    DELETE  FROM dbo.TABLAS
    WHERE   TAB_CODCIA = @CODCIA
            AND TAB_NUMTAB = @CODIGO AND TAB_TIPREG=122
GO
