IF EXISTS
(
    SELECT TOP 1
           s.SPECIFIC_NAME
    FROM INFORMATION_SCHEMA.ROUTINES s
    WHERE s.ROUTINE_TYPE = 'PROCEDURE'
          AND s.ROUTINE_NAME = 'USP_VALIDA_ARTICULO_BOLSA'
)
BEGIN
    DROP PROC [dbo].[USP_VALIDA_ARTICULO_BOLSA];
END;
GO
/*
USP_VALIDA_ARTICULO_BOLSA '01',34
USP_VALIDA_ARTICULO_BOLSA '01',35
*/
CREATE PROCEDURE [dbo].[USP_VALIDA_ARTICULO_BOLSA]
    @CODCIA CHAR(2),
    @CODART BIGINT
WITH ENCRYPTION
AS
BEGIN
    DECLARE @BOLSAS INT = 0;
    DECLARE @PRECIO MONEY = 0;
	DECLARE @PRODUCTO VARCHAR(100);
	DECLARE @IDPRODUCTO BIGINT;

    SELECT @BOLSAS = COALESCE(a.ART_BOLSAS, 0)
    FROM dbo.ARTI a
    WHERE a.ART_CODCIA = @CODCIA
          AND a.ART_KEY = @CODART;

    IF @BOLSAS <> 0
    BEGIN
        SELECT @PRECIO = COALESCE(p.PRE_PRE1, 0), @PRODUCTO = RTRIM(LTRIM(A.ART_NOMBRE)), @IDPRODUCTO = A.ART_KEY
        FROM dbo.ARTI a
            INNER JOIN dbo.PRECIOS p
                ON a.ART_CODCIA = p.PRE_CODCIA
                   AND a.ART_KEY = p.PRE_CODART
        WHERE a.ART_CODCIA = @CODCIA
              AND a.ART_KEY = 352;

			  SELECT 1 AS 'AGREGA',@IDPRODUCTO AS 'IDE',@PRODUCTO AS 'PRD',@PRECIO AS 'PRE',@BOLSAS AS 'CANT'
    END;
	ELSE
	BEGIN
	    SELECT 0 AS 'AGREGA',0 AS 'IDE','' AS 'PRD',0 AS 'PRE',0 AS 'CANT'
	END

END;

GO