IF EXISTS
(
    SELECT TOP 1
        s.SPECIFIC_NAME
    FROM INFORMATION_SCHEMA.ROUTINES s
    WHERE s.ROUTINE_TYPE = 'PROCEDURE'
          AND s.ROUTINE_NAME = 'USP_PARAMETRO_SERVICIO'
)
BEGIN
    DROP PROC [dbo].[USP_PARAMETRO_SERVICIO];
END;
GO
/*
USP_PARAMETRO_SERVICIO '01'
*/

CREATE PROCEDURE [dbo].[USP_PARAMETRO_SERVICIO]
    @CODCIA CHAR(2)
WITH ENCRYPTION
AS
SET NOCOUNT ON;
SELECT TOP 1 CAST(p.PAR_SERVICIO / 100.00 AS MONEY) AS 'servicio' FROM dbo.PARGEN p WHERE p.PAR_CODCIA = @CODCIA;

GO