--SET QUOTED_IDENTIFIER ON|OFF
--SET ANSI_NULLS ON|OFF
--exec [dbo].[USP_DOCTOVENTAS_FORMASPAGO] '01','B','1','6178'

/*
exec [dbo].[USP_DOCTOVENTAS_CAMBIARFORMAPAGO] '01','1',6178,'B','2020-10-10 00:00:00',19,2,'TARJETA DE CREDITO'
exec [dbo].[USP_DOCTOVENTAS_CAMBIARFORMAPAGO] '01','3',4414,'B','2024-08-19 00:00:00',1,2
*/
ALTER PROCEDURE [dbo].[USP_DOCTOVENTAS_CAMBIARFORMAPAGO]
    @CODCIA CHAR(2) ,
    @SERIE VARCHAR(3) ,
    @NUMERO INT ,
    @FBG CHAR(1) ,
    --@FECHA DATE ,
    --@NUMOPER INT ,
    @IDFORMAPAGO INT ,
    --@FORMAPAGO VARCHAR(30),
    @IDFORMAPAGONEW INT
    ,@CORRELATIVO INT
AS
    SET NOCOUNT ON


    --UPDATE  dbo.ALLOG
    --SET     ALL_SECUENCIA = @IDFORMAPAGO ,
    --        ALL_AUTOCON = @FORMAPAGO ,
    --        ALL_SUBTRA = @FORMAPAGO
    --WHERE   ALL_CODCIA = @CODCIA
    --        AND ALL_NUMSER = @SERIE
    --        and ALL_NUMFAC = @NUMERO
    --        AND ALL_CODTRA = 2401
    --        AND ALL_FECHA_DIA = @FECHA
    --        AND ALL_NUMOPER = @NUMOPER
    --        AND ALL_FBG = @FBG
         
            update COMPROBANTE_FORMAPAGO set IDFORMAPAGO = @IDFORMAPAGONEW
            where CODCIA = @CODCIA and TIPODOCTO = @FBG and SERIE = @SERIE and NUMERO = @NUMERO AND IDFORMAPAGO = @IDFORMAPAGO AND CORRELATIVO = @CORRELATIVO;
            

