IF EXISTS ( SELECT TOP 1
                    S.SPECIFIC_NAME
            FROM    information_schema.routines s
            WHERE   s.ROUTINE_TYPE = 'PROCEDURE'
                    AND S.ROUTINE_NAME = 'WEB_MESAbyZONAS' )
    BEGIN
        DROP PROC [dbo].[WEB_MESAbyZONAS]
    END
GO
/*
exec WEB_MESAbyZONAS @IDZONA=2,@CODCIA=N'01'
*/
CREATE PROCEDURE [dbo].[WEB_MESAbyZONAS]
    @IDZONA INT ,
    @CODCIA CHAR(2)
AS 
    SET NOCOUNT ON
   
  
    SELECT  RTRIM(LTRIM(M.MES_CODMES)) AS 'IDEMESA' ,
            --RTRIM(LTRIM(M.MES_DESCRIP)) + ' - COMENSALES: ' + CAST(m.MES_COMENSALES AS VARCHAR(20)) AS 'MESA' ,
			RTRIM(LTRIM(M.MES_DESCRIP))  AS 'MESA' ,
            RTRIM(LTRIM(M.MES_ESTADO)) AS 'ESTADO',
			CAST(COALESCE(M.MES_COMENSALES,0) AS VARCHAR(10)) AS 'COMENSALES'
    FROM    dbo.MESAS m
    WHERE   M.MES_CODCIA = @CODCIA
            AND M.MES_CODZON = @IDZONA
    ORDER BY M.MES_DESCRIP
    
   


GO